/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wizzardo_epoll_EpollServer */

#ifndef _Included_com_wizzardo_epoll_EpollServer
#define _Included_com_wizzardo_epoll_EpollServer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wizzardo_epoll_EpollServer_MIN_PRIORITY
#define com_wizzardo_epoll_EpollServer_MIN_PRIORITY 1L
#undef com_wizzardo_epoll_EpollServer_NORM_PRIORITY
#define com_wizzardo_epoll_EpollServer_NORM_PRIORITY 5L
#undef com_wizzardo_epoll_EpollServer_MAX_PRIORITY
#define com_wizzardo_epoll_EpollServer_MAX_PRIORITY 10L
/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    listen
 * Signature: (Ljava/lang/String;ILjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_wizzardo_epoll_EpollServer_listen
  (JNIEnv *, jobject, jstring, jstring, jint, jobject);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    stopListening
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wizzardo_epoll_EpollServer_stopListening
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    waitForEvents
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_wizzardo_epoll_EpollServer_waitForEvents
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    startWriting
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wizzardo_epoll_EpollServer_startWriting
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    stopWriting
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wizzardo_epoll_EpollServer_stopWriting
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wizzardo_epoll_EpollServer_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    read
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_com_wizzardo_epoll_EpollServer_read
  (JNIEnv *, jobject, jint, jlong, jint, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    write
 * Signature: (IJII)I
 */
JNIEXPORT jint JNICALL Java_com_wizzardo_epoll_EpollServer_write
  (JNIEnv *, jobject, jint, jlong, jint, jint);

/*
 * Class:     com_wizzardo_epoll_EpollServer
 * Method:    getAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_wizzardo_epoll_EpollServer_getAddress
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
